# Generated by Django 3.2.6 on 2021-10-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lineas',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('creadorpor', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='transporte')),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'linea',
                'verbose_name_plural': 'lineas',
            },
        ),
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotolinea')),
                ('idnombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lineas.lineas')),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
            },
        ),
    ]
