# Generated by Django 3.2.6 on 2021-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lineas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
