# Generated by Django 3.2.6 on 2021-10-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lineas', '0002_fotos_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='nombre',
        ),
    ]
