# Generated by Django 3.2.6 on 2021-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lineas', '0004_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='email',
        ),
        migrations.AddField(
            model_name='pictures',
            name='linea',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
