# Generated by Django 3.2.6 on 2021-12-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('destino', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('salida', models.DateField()),
                ('llegada', models.DateField()),
                ('created', models.DateField(auto_now=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='boletos')),
            ],
            options={
                'verbose_name': 'boleto',
                'verbose_name_plural': 'boletos',
            },
        ),
    ]
