# Generated by Django 3.2.6 on 2021-12-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_remove_usuarios_modificado'),
        ('Boletos', '0002_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='comprador',
            fields=[
                ('DD', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.usuarios')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
            },
        ),
    ]
