# Generated by Django 3.2.6 on 2021-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletos', '0004_auto_20211216_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficial',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oficial',
            name='campo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
