# Generated by Django 3.2.6 on 2022-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletos', '0008_auto_20211227_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficial',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
