# Generated by Django 3.2.6 on 2022-01-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletos', '0009_oficial_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='mail',
            field=models.CharField(max_length=100),
        ),
    ]
