# Generated by Django 3.2.6 on 2022-01-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_alter_usuarios_foto'),
        ('Boletos', '0010_alter_oficial_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('campo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.usuarios')),
            ],
            options={
                'verbose_name': 'tabla',
                'verbose_name_plural': 'tablas',
            },
        ),
    ]
