# Generated by Django 3.2.6 on 2021-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=55, max_length=100),
            preserve_default=False,
        ),
    ]
