# Generated by Django 3.2.6 on 2021-10-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_usuarios_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
    ]
