# Generated by Django 3.2.6 on 2021-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_remove_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
