# Generated by Django 3.2.6 on 2021-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='origen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
