# Generated by Django 3.2.6 on 2021-12-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_auto_20211029_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='modificado',
        ),
    ]
